### ISSUE TITLE
besthits output is missing

### ISSUE THREAD

**Issue by vojtace** [loosolab/UROPA#9]
Hello,
according to the manual there should be three output .bed files when using multiple queries: allhits, finalhits, and besthits. When I run uropa the besthits output is missing. There is no error while executing uropa. I tried it with my data and also with the example data from the manual, with the same result. My version of uropa: 4.0.2
Any advice how to get the besthits file? Thanks!

**Comment by msbentsen** [comment]
Hi vojtace,

The besthits file is deprecated since 3.0.0, but we forgot to remove it from the documentation. Sorry about the confusion! The besthits file is no longer created, but instead, you can use ` --output-by-query` to get the annotations for each individual query. 

I have updated the documentation here on github, but still need to update it on readthedocs. Until then, the docs on output files is available [here](https://github.com/loosolab/UROPA/blob/master/docs_rst/output.rst). Hope that clears up the question.

**Comment by vojtace** [comment]
Hi, thank you for explaining. The `--output-by-query` works fine.
I also noticed that using the `-d` parameter results in some more output files, which also not explained in the manual.

**Comment by msbentsen** [comment]
Yes, for debugging purposes (`-d/--debug`), any temporary files are kept within the output folder - but I wouldn't call these regular output files. That is why they are not described in the manual. So if you run uropa with `-d`, you can safely ignore these files.
